// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrdinarioWebDefinitivoAhora.Data;

#nullable disable

namespace OrdinarioWebDefinitivoAhora.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210204033_uno")]
    partial class uno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.CancelacionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MemoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCancela")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MemoId");

                    b.ToTable("Cancelaciones");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.FolioModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Folios");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.MemoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Asunto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("De")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Estatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("TEXT");

                    b.Property<int>("FolioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Para")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioRegistro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FolioId")
                        .IsUnique();

                    b.ToTable("Memos");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NumEmpleado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.CancelacionModel", b =>
                {
                    b.HasOne("OrdinarioWebDefinitivoAhora.Models.MemoModel", "Memo")
                        .WithMany("Cancelaciones")
                        .HasForeignKey("MemoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Memo");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.MemoModel", b =>
                {
                    b.HasOne("OrdinarioWebDefinitivoAhora.Models.FolioModel", "Folio")
                        .WithOne("Memo")
                        .HasForeignKey("OrdinarioWebDefinitivoAhora.Models.MemoModel", "FolioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folio");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.FolioModel", b =>
                {
                    b.Navigation("Memo");
                });

            modelBuilder.Entity("OrdinarioWebDefinitivoAhora.Models.MemoModel", b =>
                {
                    b.Navigation("Cancelaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
